name: rpi_gpsd_chrony
services:
    rpi-gpsd:
        stdin_open: true
        tty: true
        env_file:
            - config.env
        devices:
            - /dev/ttyACM0
            - /dev/pps0
        ports:
            - 123:123
        container_name: gpsd-chrony
        cap_add:
            - SYS_TIME
        privileged: true
        image: arluhdev/docker-gpsd-chrony:latest
        volumes:
            - chrony_logs:/var/log/chrony
            - chrony_drift:/var/lib/chrony
            - ./chrony_config:/etc/chrony
            - ./entrypoint.sh:/entrypoint.sh:ro

volumes:
    chrony_logs:

    chrony_drift:
